<?php

namespace App\Enums;

enum TicketClassificationEnum: string
{
    case ACCOUNT_CREATION = 'ACCOUNT_CREATION';
    case ACCOUNT_DEACTIVATION = 'ACCOUNT_DEACTIVATION';
    case ACCESS_FILES = 'ACCESS_FILES';
    case ANTIVIRUS_RENEWAL = 'ANTIVIRUS_RENEWAL';
    case APPS_INSTALLATION = 'APPS_INSTALLATION';
    case ASSET_PURCHASE = 'ASSET_PURCHASE';
    case BIOMETRIC = 'BIOMETRIC';
    case BRANCH_MASTER_FILE_REPORTS = 'BRANCH_MASTER_FILE_REPORTS';
    case CAMERA = 'CAMERA';
    case CAR_TRACK = 'CAR_TRACK';
    case CASH_DRAWER = 'CASH_DRAWER';
    case CCTV = 'CCTV';
    case CCTV_ACCESS = 'CCTV_ACCESS';
    case CCTV_FOOTAGE = 'CCTV_FOOTAGE';
    case CCTV_INSTALLATION = 'CCTV_INSTALLATION';
    case COMPANY_EVENTS = 'COMPANY_EVENTS';
    case DATA_BACKUP = 'DATA_BACKUP';
    case DISPLAY = 'DISPLAY';
    case DOMAIN_RENEWAL = 'DOMAIN_RENEWAL';
    case DVR = 'DVR';
    case EMAIL = 'EMAIL';
    case EMAIL_CREATION = 'EMAIL_CREATION';
    case EMPLOYEE_LIST = 'EMPLOYEE_LIST';
    case FIREWALL_RENEWAL = 'FIREWALL_RENEWAL';
    case FORTICLIENT = 'FORTICLIENT';
    case GRAB = 'GRAB';
    case HARDWARE = 'HARDWARE';
    case HRS_ACCESS_RIGHTS = 'HRS_ACCESS_RIGHTS';
    case HRS_PROBLEM = 'HRS_PROBLEM';
    case HRS_REPORTS = 'HRS_REPORTS';
    case HRS_UPLOADING = 'HRS_UPLOADING';
    case IBMIS_ACCESS = 'IBMIS_ACCESS';
    case IBMIS_CODE = 'IBMIS_CODE';
    case IBMIS_REPORT = 'IBMIS_REPORT';
    case IBMIS_UPLOADING = 'IBMIS_UPLOADING';
    case INSTALLATION = 'INSTALLATION';
    case INTERNET = 'INTERNET';
    case INTERNET_ACCESS = 'INTERNET_ACCESS';
    case INTERNET_APPLICATION = 'INTERNET_APPLICATION';
    case IPAD = 'IPAD';
    case JBIMS = 'JBIMS';
    case JBIMS_ACCESS_RIGHTS = 'JBIMS_ACCESS_RIGHTS';
    case JBIMS_PORTAL = 'JBIMS_PORTAL';
    case JBIMS_REPORT = 'JBIMS_REPORT';
    case JGC_PORTAL = 'JGC_PORTAL';
    case LOCATION_TRANSFER = 'LOCATION_TRANSFER';
    case MANHATTAN = 'MANHATTAN';
    case MEETINGS = 'MEETINGS';
    case M365_CONCERN = 'M365_CONCERN';
    case M365_RENEWAL = 'M365_RENEWAL';
    case MNSR_SALES_REPORT = 'MNSR_SALES_REPORT';
    case MOBILE = 'MOBILE';
    case MOUSE = 'MOUSE';
    case NEW_CCTV = 'NEW_CCTV';
    case NEW_DESKTOP = 'NEW_DESKTOP';
    case NEW_LAPTOP = 'NEW_LAPTOP';
    case NEW_POS_FRANCHISE_INSTALLATION = 'NEW_POS_FRANCHISE_INSTALLATION';
    case NEW_POS_COMPANY_OWNED_INSTALLATION = 'NEW_POS_COMPANY_OWNED_INSTALLATION';
    case NEW_TELEPHONE_HANDSET = 'NEW_TELEPHONE_HANDSET';
    case NETWORK_CONCERN = 'NETWORK_CONCERN';
    case ONLINE_DTR = 'ONLINE_DTR';
    case ONLINE_ORDERING_CONCERN = 'ONLINE_ORDERING_CONCERN';
    case ONLINE_ORDERING_USER_REGISTRATION = 'ONLINE_ORDERING_USER_REGISTRATION';
    case PARTS_REPLACEMENT = 'PARTS_REPLACEMENT';
    case PAGER_SYSTEM = 'PAGER_SYSTEM';
    case PAGING_SYSTEM = 'PAGING_SYSTEM';
    case PAYROLL = 'PAYROLL';
    case PBO = 'PBO';
    case POS_ACCESS_RIGHTS = 'POS_ACCESS_RIGHTS';
    case POS_INSTALLATION = 'POS_INSTALLATION';
    case POS_INTERNET_UPDATE = 'POS_INTERNET_UPDATE';
    case POS_REGISTRATION = 'POS_REGISTRATION';
    case POS_REPORTS = 'POS_REPORTS';
    case POS_REQUEST = 'POS_REQUEST';
    case POS_SALES_REPORT = 'POS_SALES_REPORT';
    case POS_SERVICE = 'POS_SERVICE';
    case PRINTER = 'PRINTER';
    case PROCESS_PAYMENT = 'PROCESS_PAYMENT';
    case PRODUCT_COSTING = 'PRODUCT_COSTING';
    case PRODUCT_COSTING_UPLOADING = 'PRODUCT_COSTING_UPLOADING';
    case PURCHASE_ORDER = 'PURCHASE_ORDER';
    case REPLICATION = 'REPLICATION';
    case REPLICATION_ERROR = 'REPLICATION_ERROR';
    case REMOTE_ACCOUNT_CREATION = 'REMOTE_ACCOUNT_CREATION';
    case ROUTER = 'ROUTER';
    case SAP_ACCESS_RIGHTS = 'SAP_ACCESS_RIGHTS';
    case SAP_BP_REGISTRATION = 'SAP_BP_REGISTRATION';
    case SAP_DTIV_UPLOADING = 'SAP_DTIV_UPLOADING';
    case SAP_HANGUP = 'SAP_HANGUP';
    case SAP_PRINT_LAYOUT = 'SAP_PRINT_LAYOUT';
    case SAP_PORTAL = 'SAP_PORTAL';
    case SAP_REPORTS = 'SAP_REPORTS';
    case SAP_SB_PO_UPLOADING = 'SAP_SB_PO_UPLOADING';
    case SALES_UPLOADING = 'SALES_UPLOADING';
    case SERVER = 'SERVER';
    case SERVER_AIRCON = 'SERVER_AIRCON';
    case SERVER_CONCERN = 'SERVER_CONCERN';
    case SERVICE_DELIVERY = 'SERVICE_DELIVERY';
    case SSL_RENEWAL = 'SSL_RENEWAL';
    case SSL_SETUP = 'SSL_SETUP';
    case STORE_PROCEDURE = 'STORE_PROCEDURE';
    case TABLET = 'TABLET';
    case TELEPHONE = 'TELEPHONE';
    case TOOL_OF_TRADE = 'TOOL_OF_TRADE';
    case TOOL_OF_TRADE_BORROWED = 'TOOL_OF_TRADE_BORROWED';
    case TOUCHPAD = 'TOUCHPAD';
    case TRAINING = 'TRAINING';
    case TREASURY_REPORTS = 'TREASURY_REPORTS';
    case UPS = 'UPS';
    case USER_DATA_ACCESS = 'USER_DATA_ACCESS';
    case WEBSITE_UPDATE = 'WEBSITE_UPDATE';
    case WEEKLY_REPORT = 'WEEKLY_REPORT';
    case WINDOWS_EXPLORER = 'WINDOWS_EXPLORER';
    case WIFI_ACCESS_POINT = 'WIFI_ACCESS_POINT';

    public function label(): string
    {
        return match($this) {
            self::ACCOUNT_CREATION => 'Account Creation',
            self::ACCOUNT_DEACTIVATION => 'Account Deactivation',
            self::ACCESS_FILES => 'Access Files',
            self::ANTIVIRUS_RENEWAL => 'Antivirus Renewal',
            self::APPS_INSTALLATION => 'Apps Installation',
            self::ASSET_PURCHASE => 'Asset Purchase',
            self::BIOMETRIC => 'Biometric',
            self::BRANCH_MASTER_FILE_REPORTS => 'Branch Master File Reports',
            self::CAMERA => 'Camera',
            self::CAR_TRACK => 'Car Track',
            self::CASH_DRAWER => 'Cash Drawer',
            self::CCTV => 'CCTV',
            self::CCTV_ACCESS => 'CCTV Access',
            self::CCTV_FOOTAGE => 'CCTV Footage',
            self::CCTV_INSTALLATION => 'CCTV Installation',
            self::COMPANY_EVENTS => 'Company Events',
            self::DATA_BACKUP => 'Data Backup',
            self::DISPLAY => 'Display Issue',
            self::DOMAIN_RENEWAL => 'Domain Renewal',
            self::DVR => 'DVR',
            self::EMAIL => 'Email',
            self::EMAIL_CREATION => 'Email Creation',
            self::EMPLOYEE_LIST => 'Employee List',
            self::FIREWALL_RENEWAL => 'Firewall Renewal',
            self::FORTICLIENT => 'FortiClient',
            self::GRAB => 'Grab',
            self::HARDWARE => 'Hardware Issue',
            self::HRS_ACCESS_RIGHTS => 'HRS Access Rights',
            self::HRS_PROBLEM => 'HRS Problem',
            self::HRS_REPORTS => 'HRS Reports',
            self::HRS_UPLOADING => 'HRS Uploading',
            self::IBMIS_ACCESS => 'IBMIS Access',
            self::IBMIS_CODE => 'IBMIS Code',
            self::IBMIS_REPORT => 'IBMIS Report',
            self::IBMIS_UPLOADING => 'IBMIS Uploading',
            self::INSTALLATION => 'Installation',
            self::INTERNET => 'Internet',
            self::INTERNET_ACCESS => 'Internet Access',
            self::INTERNET_APPLICATION => 'Internet Application',
            self::IPAD => 'iPad',
            self::JBIMS => 'JBIMS',
            self::JBIMS_ACCESS_RIGHTS => 'JBIMS Access Rights',
            self::JBIMS_PORTAL => 'JBIMS Portal',
            self::JBIMS_REPORT => 'JBIMS Report',
            self::JGC_PORTAL => 'JGC Portal',
            self::LOCATION_TRANSFER => 'Location Transfer',
            self::MANHATTAN => 'Manhattan',
            self::MEETINGS => 'Meetings',
            self::M365_CONCERN => 'M365 Concern',
            self::M365_RENEWAL => 'M365 Renewal',
            self::MNSR_SALES_REPORT => 'MNSR Sales Report',
            self::MOBILE => 'Mobile',
            self::MOUSE => 'Mouse Issue',
            self::NEW_CCTV => 'New CCTV',
            self::NEW_DESKTOP => 'New Desktop',
            self::NEW_LAPTOP => 'New Laptop',
            self::NEW_POS_FRANCHISE_INSTALLATION => 'New POS Franchise Installation',
            self::NEW_POS_COMPANY_OWNED_INSTALLATION => 'New POS Company Owned Installation',
            self::NEW_TELEPHONE_HANDSET => 'New Telephone Handset',
            self::NETWORK_CONCERN => 'Network Concern',
            self::ONLINE_DTR => 'Online DTR',
            self::ONLINE_ORDERING_CONCERN => 'Online Ordering Concern',
            self::ONLINE_ORDERING_USER_REGISTRATION => 'Online Ordering User Registration',
            self::PARTS_REPLACEMENT => 'Parts Replacement',
            self::PAGER_SYSTEM => 'Pager System',
            self::PAGING_SYSTEM => 'Paging System',
            self::PAYROLL => 'Payroll',
            self::PBO => 'PBO',
            self::POS_ACCESS_RIGHTS => 'POS Access Rights',
            self::POS_INSTALLATION => 'POS Installation',
            self::POS_INTERNET_UPDATE => 'POS Internet Update',
            self::POS_REGISTRATION => 'POS Registration',
            self::POS_REPORTS => 'POS Reports',
            self::POS_REQUEST => 'POS Request',
            self::POS_SALES_REPORT => 'POS Sales Report',
            self::POS_SERVICE => 'POS Service',
            self::PRINTER => 'Printer',
            self::PROCESS_PAYMENT => 'Process Payment',
            self::PRODUCT_COSTING => 'Product Costing',
            self::PRODUCT_COSTING_UPLOADING => 'Product Costing Uploading',
            self::PURCHASE_ORDER => 'Purchase Order',
            self::REPLICATION => 'Replication',
            self::REPLICATION_ERROR => 'Replication Error',
            self::REMOTE_ACCOUNT_CREATION => 'Remote Account Creation',
            self::ROUTER => 'Router',
            self::SAP_ACCESS_RIGHTS => 'SAP Access Rights',
            self::SAP_BP_REGISTRATION => 'SAP BP Registration',
            self::SAP_DTIV_UPLOADING => 'SAP DTIV Uploading',
            self::SAP_HANGUP => 'SAP Hang Up',
            self::SAP_PRINT_LAYOUT => 'SAP Print Layout',
            self::SAP_PORTAL => 'SAP Portal',
            self::SAP_REPORTS => 'SAP Reports',
            self::SAP_SB_PO_UPLOADING => 'SAP SB/PO Uploading',
            self::SALES_UPLOADING => 'Sales Uploading',
            self::SERVER => 'Server',
            self::SERVER_AIRCON => 'Server Aircon',
            self::SERVER_CONCERN => 'Server Concern',
            self::SERVICE_DELIVERY => 'Service Delivery',
            self::SSL_RENEWAL => 'SSL Renewal',
            self::SSL_SETUP => 'SSL Setup',
            self::STORE_PROCEDURE => 'Store Procedure',
            self::TABLET => 'Tablet',
            self::TELEPHONE => 'Telephone',
            self::TOOL_OF_TRADE => 'Tool of Trade',
            self::TOOL_OF_TRADE_BORROWED => 'Tool of Trade Borrowed',
            self::TOUCHPAD => 'Touchpad',
            self::TRAINING => 'Training',
            self::TREASURY_REPORTS => 'Treasury Reports',
            self::UPS => 'UPS',
            self::USER_DATA_ACCESS => 'User Data Access',
            self::WEBSITE_UPDATE => 'Website Update',
            self::WEEKLY_REPORT => 'Weekly Report',
            self::WINDOWS_EXPLORER => 'Windows Explorer',
            self::WIFI_ACCESS_POINT => 'Access Point',
        };
    }
}
